CREATE TABLE events (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name        VARCHAR(255) NOT NULL,
                        max_seats   INTEGER NOT NULL,
                        created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT chk_max_seats_positive CHECK (max_seats > 0)
);