apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: erp
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: event_registration
  DB_USER: event_user
  DB_PASSWORD: event_pass
  DB_SSLMODE: disable
  APP_JWT_SECRET: "local-k8s-jwt-secret-change-me-32chars"
