spring:
  application:
    name: event-registration
  datasource:
    url: jdbc:h2:mem:event_registration;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: 8080

springdoc:
   swagger-ui:
     path: /swagger-ui.html
   api-docs:
     path: /v3/api-docs