spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_registration
    username: event_user
    password: event_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: false

server:
  port: 8080